sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 7.1

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit -c ./phpunit.xml.dist
  - vendor/bin/phpcs --standard=PSR2 src

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false
